spring:
  cloud:
    gateway:
      routes:
        - id: posts
          uri: http://localhost:18081
          predicates:
            - Path=/posts/**
#          filters:
#            - name: GlobalFilter
#              args:
#                baseMessage: Spring Cloud Gateway PostsFilter
#                preLogger: true
#                postLogger: true
        - id: user
          uri: http://localhost:18082
          predicates:
            - Path=/user/**