spring:
  application:
    name: app-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: posts
          uri: lb://post-service
          predicates:
            - Path=/posts/**
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback
        - id: posts-fallback
          uri: http://192.168.0.177:14080/
          predicates:
            - Path=/fallback

        #          filters:
#            - name: GlobalFilter
#              args:
#                baseMessage: Spring Cloud Gateway PostsFilter
#                preLogger: true
#                postLogger: true
        - id: user
          uri: http://localhost:18082
          predicates:
            - Path=/user/**
management:
  endpoints:
    web:
      exposure:
        include:
          - "gateway"
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.0.215:8880/eureka/

logging:
  level:
    root: debug